#########################################################################
# TrasparenzAI - MCP Server                                             #
# Configurazione per l'avvio di MCP Server                              #
#########################################################################

services:
  mcp-server:
    image: ghcr.io/trasparenzai/mcp-server:latest
    container_name: mcp-server
    ports:
      - 8080
    environment:
    #- server.servlet.context-path=/mcp-server
    # Configurazione Autenticazione OAuth2 come Resource Server
    - spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dica33.ba.cnr.it/keycloak/realms/trasparenzai
    # Base URL del servizio Public Sites (override con env/profili se necessario)
    #- public-sites.base-url=https://dica33.ba.cnr.it/public-sites-service
    #- public-sites.company-search-max-results=100
    # Base URL del servizio Results (override con env/profili se necessario)
    #- result-service.base-url=https://dica33.ba.cnr.it/result-service
    # Base URL del servizio Conductor (override con env/profili se necessario)
    #- conductor.base-url=https://monitorai.ba.cnr.it/conductor-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.mcp-server.entrypoints=websecure"
    #  - "traefik.http.routers.mcp-server.rule=Host(`dica33.ba.cnr.it`) && PathPrefix(`/mcp-server`)"
    #  - "traefik.http.routers.mcp-server.tls.certresolver=myresolver"
    #  - "traefik.http.routers.mcp-server.middlewares=cors-mcp-server"
    #  - "traefik.http.middlewares.cors-mcp-server.headers.accessControlAllowOriginListRegex=(.*?)"
    #  - "traefik.http.middlewares.cors-mcp-server.headers.accesscontrolallowheaders=*"
    #networks:
    #  - traefik_default

#networks:
#  traefik_default:
#    external: true