spring.application.name=TrasparenzAI MCP Server

# Base URL del servizio Public Sites (override con env/profili se necessario)
public-sites.base-url=https://dica33.ba.cnr.it/public-sites-service

public-sites.company-search-max-results=100

# Base URL del servizio Results (override con env/profili se necessario)
result-service.base-url=https://dica33.ba.cnr.it/result-service

# Base URL del servizio Conductor (override con env/profili se necessario)
conductor.base-url=https://monitorai.ba.cnr.it/conductor-server

spring.jackson.deserialization.adjust-dates-to-context-time-zone=false

spring.ai.mcp.server.protocol=STREAMABLE

server.port=8081

# Turn on OAuth2 Resource Server
# This assumes we have an Authorization Server available
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dica33.ba.cnr.it/keycloak/realms/trasparenzai
