spring.application.name=TrasparenzAI MCP Server

# Base URL del servizio Public Sites (override con env/profili se necessario)
public-sites.base-url=https://dica33.ba.cnr.it/public-sites-service

public-sites.company-search-max-results=1000

# Base URL del servizio Results (override con env/profili se necessario)
result-service.base-url=https://dica33.ba.cnr.it/result-service

# Base URL del servizio Conductor (override con env/profili se necessario)
conductor.base-url=https://monitorai.ba.cnr.it/conductor-server

spring.jackson.deserialization.adjust-dates-to-context-time-zone=false

spring.ai.mcp.server.protocol=STREAMABLE

